version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $IMAGE_REPO_URI
  build:
    commands:
      - cd ./Backend/my-app
      - echo Build started on `date`
      - echo Building the Backend Docker image...
      - docker build -t myapp-backend:$IMAGE_TAG_BACKEND .
      - docker tag myapp-backend:$IMAGE_TAG_BACKEND $IMAGE_REPO_URI:$IMAGE_TAG_BACKEND
      - cd ../../Frontend/my-app
      - echo Build started on `date`
      - echo Building the Frontend Docker image...
      - docker build -t myapp-frontend:$IMAGE_TAG_FRONTEND .
      - docker tag myapp-frontend:$IMAGE_TAG_FRONTEND $IMAGE_REPO_URI:$IMAGE_TAG_FRONTEND

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_URI:$IMAGE_TAG_BACKEND
      - docker push $IMAGE_REPO_URI:$IMAGE_TAG_FRONTEND