version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - cd ./Backend/my-app
      - echo Installing python packages...
      - python -m venv backend-venv
      - . backend-venv/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - echo run tests...
      - python -m pytest